# Generated by Django 5.2.4 on 2025-07-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0002_kategori_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(blank=True, max_length=100)),
                ('gambar', models.ImageField(upload_to='banner/')),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
    ]
