# Generated by Django 5.2.4 on 2025-07-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0003_bannerheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='pilihan',
            field=models.BooleanField(default=False),
        ),
    ]
