# Generated by Django 5.2.4 on 2025-07-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0004_berita_pilihan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBerjalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.TextField(verbose_name='Teks Berjalan')),
            ],
        ),
    ]
