# Generated by Django 5.2.4 on 2025-08-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0007_alter_berita_isi'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
