# Generated by Django 5.2.4 on 2026-05-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0008_berita_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='is_headline',
            field=models.BooleanField(default=False),
        ),
    ]
