# Generated by Django 5.2.4 on 2026-05-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0009_berita_is_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
